### ISSUE TITLE
YouTube audio is truncated.

### ISSUE THREAD

**Issue by FeralMina** [CherokeeLanguage/Cherokee-Language-Lessons-1#2]
On page 10 of the book, it directs the reader to now begin the audio and continue until the audio instructs otherwise. It repeats this same instruction in the written description of the audio on YT, and at the beginning  of the first section of audio. But at which point are students supposed to return to the book? I’m in the fourth piece of audio and still haven’t been instructed to return to the book. 

In a possibly related matter, it seems like all of the first four sections of audio are cut off at the end. EDIT - I’m unsure if other audio sections are cut off also, or not.

**Comment by michael-conrad** [comment]
Yes the YouTube audio is truncated. Very odd. I'll need to figure out what's wrong there and upload new videos.

The audio on [CherokeeLessons.com](https://www.cherokeelessons.com/lesson-audio/cherokee-language-lessons-1---audio-exercises/) is intact.

All audio sessions should end with:

> This concludes this audio exercise.
> Production copyright 2022 by Michael Conrad.
> This work is licensed to you under the Creative Commons Attribution Share-Alike license.
> To obtain a copy of this license please look up Creative Commons online.
> You are free to share, copy, and distribute this work.
> If you alter, build upon, or transform this work, you must use the same license on the resulting work.
> This audio file was produced on DATE by Michael Conrad.

Ok, this is what I show for which tracks should be indicating when to switch back to the book.

```
0001: 
0002: 
0003: 
0004: Complete the lesson material through the end of chapter 4.
0005: 
0006: Complete the lesson material through the end of chapter 5.
0007: Complete the lesson material through the end of chapter 6.
0008: Complete the lesson material through the end of chapter 8.
0009: 
0010: Complete the lesson material through the end of chapter 9.
0011: Complete the lesson material through the end of chapter 10.
0012: 
0013: Complete the lesson material through the end of chapter 11.
0014: Complete the lesson material through the end of chapter 12.
0015: 
0016: 
0017: Complete the lesson material through the end of chapter 14.
0018: Complete the lesson material through the end of chapter 17.
0019: Complete the lesson material through the end of chapter 18.
0020: Complete the lesson material through the end of chapter 19.
0021: Complete the lesson material through the end of chapter 20.
0022: Complete the lesson material through the end of chapter 21.
0023: Complete the lesson material through the end of chapter 22.
```

The Syllabary Dictation audio is not part of that and is separate with a separate link in the book.

**Comment by michael-conrad** [comment]
ᎰᏩ,

I have a fix for the issue. It was caused by adding subtitles while creating the initial video.

I've changed it so that the subtitles are added after the initial video is created to prevent this issue.

New video is being generated now. I'll add a note here after I get it all uploaded to YouTube and have the playlist updated.

**Comment by michael-conrad** [comment]
New videos have been created and I've started uploading them to YouTube.

The old videos have been deleted.

The playlist should now only show the new complete videos.

CODE REF: https://github.com/CherokeeLanguage/audio-lessons-generator-python/commit/9af574ad5f5c6bbdcf3bb7c341ee02167f74bef2

**Comment by michael-conrad** [comment]
@FeralMina ᏩᏙ!
